# This workflow will make a release based on Conventional Commit Messages
# This should trigger the build workflow

name: 'Release Maker'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Automate release with Conventional Commit Messages
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: release-please-action