# This workflow will parse the code and the dependencies to find vulnerabilities

name: 'Security Checker'

on: workflow_dispatch

jobs:
  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-20@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}